platform :ios, '7.0'

pod 'AFNetworking',         '3.0.4'
pod 'wpxmlrpc',             '0.8.1'
pod 'MBProgressHUD',        '0.9.1'
pod 'SFHFKeychainUtils',    '0.0.1'
pod 'iOS-Slide-Menu',       '1.5'
