platform :ios, '8.0'

target 'odooMobile' do
# Objective-C
    pod 'AFNetworking',         '3.0.4'
    pod 'wpxmlrpc',             '0.8.1'
    pod 'MBProgressHUD',        '0.9.1'
    pod 'SFHFKeychainUtils',    '0.0.1'
    pod 'iOS-Slide-Menu',       '1.5'
end
